### ISSUE TITLE
seq and annotation

### ISSUE THREAD

**Issue by ilaydagulmez** [almeidasilvaf/doubletrouble#2]
Hi again,

When I try the **pdata <- process_input(seq,annotation)** command, I got the error like this:

**Error in check_list_names(seq, annotation) : 
 Names of list elements in 'seq' and 'annotation' must match.**

For protein seq and annotation files, I used the Augustus tool for this sample. 

Do you have any suggestions to help me resolve this issue? Thank you for your time.

Best regards

**Comment by almeidasilvaf** [comment]
Hi, @ilaydagulmez 

Could you show what your `seq` and `annotation` objects look like with a [reprex](https://reprex.tidyverse.org/)? Importantly, your `seq` object should have the same number of sequences as there are genes in your `annot` object. In other words, you must have only one protein sequence per gene (translated from primary transcripts).

Best,
Fabricio

**Comment by ilaydagulmez** [comment]
Hi Fabricio,

Thanks for the quick response, here are my inputs: I don't know why but reprex didn't show annotation file,

My sample has 2n=4x=68 chromosome number so maybe it would be difficult to understand genes and number of seq.

<img width="686" alt="Ekran Resmi 2024-03-14 12 14 18" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/a351d42d-f046-4303-a11f-e8148b897730">
<img width="718" alt="Ekran Resmi 2024-03-14 12 15 00" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/96027f69-2610-4561-866d-2f5604f0974d">
<img width="511" alt="Ekran Resmi 2024-03-14 12 19 00" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/be33b2b2-b38b-4146-aab0-a1aa35ba859b">
<img width="517" alt="Ekran Resmi 2024-03-14 12 18 43" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/837bca47-dab1-4dac-9ecd-125e2e2eace9">

**Comment by almeidasilvaf** [comment]
Can you show the output of the code below?

```r
names(annotation)
names(seq)

annotation[[1]][annotation[[1]]$type == "gene"]
```

**Comment by ilaydagulmez** [comment]
Sorry for my late return,

Here is the output:
<img width="415" alt="Ekran Resmi 2024-03-14 16 21 31" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/1962ee56-5996-4077-9737-927e438d476f">
<img width="531" alt="Ekran Resmi 2024-03-14 16 21 53" src="https://github.com/almeidasilvaf/doubletrouble/assets/163100594/40277923-906a-45a3-b9af-d06376e4f3fc">


Thanks for your time.

**Comment by almeidasilvaf** [comment]
Hi,

I'm sorry, but I can hardly see anything there. The screenshot cropped the `GRanges` object. Could you please write a reprex? A screenshot is not a reprex.

One thing I can see, though, is that names of your list elements are different - "20628_8" for `annotation`, and "20628_8.aa" for `seq`. These names have to be exactly equal, so that one object can be linked to another. Could you try to fix that and check if that is the source of the error? 

Best,
Fabricio

**Comment by ilaydagulmez** [comment]
Hi, 
Thanks for your quick response. After wrote this message, I changed the annotation and seq named so these are exactly equal but there is still a problem here.
When I wrote reprex I saw just this: 

seq
#> function (...) 
#> UseMethod("seq")
#> <bytecode: 0x128e42b20>
#> <environment: namespace:base>

Thanks for your time

**Comment by almeidasilvaf** [comment]
Hi,

Have you taken a look at the documentation of the reprex package? You can find it here: https://reprex.tidyverse.org/

For short, I usually do as follows: 
1. Write the code that leads to the error in an R script (.R file)
2. Select all the code and copy (CTRL+C). You copy the code, it will be saved to your clipboard.
3. On the console, I run: `reprex::reprex()`. The function `reprex::reprex()` will automatically run the code in your clipboard and return a nicely-formatted .md document that you can paste here. Alternatively, you can pass the path to the .R file you wrote to the `reprex::reprex()` function.

Best,
Fabricio

**Comment by ilaydagulmez** [comment]
Hi,
Thank you so much for your help, I'm not good at R script, I use Python and Linux for analysis. I appreciate your help. Now I'm gonna close the issue and try to run this wonderful tool! 

Best regards,
İlayda
