### ISSUE TITLE
Is there any quickly tutorial of  doubletrouble for finding gene duplication?

### ISSUE THREAD

**Issue by Chenglin20170390** [almeidasilvaf/doubletrouble#3]
Hi, Is there any quicky tutorial of  doubletrouble for finding gene duplication?

**Comment by almeidasilvaf** [comment]
Hi, @Chenglin20170390 

Is the vignette not what you mean? You can find the vignette here: 

1. Bioconductor website: https://bioconductor.org/packages/release/bioc/vignettes/doubletrouble/inst/doc/doubletrouble_vignette.html
2. doubletrouble's pkgdown website: https://almeidasilvaf.github.io/doubletrouble/articles/doubletrouble_vignette.html

Best,
Fabricio

**Comment by Chenglin20170390** [comment]
> 1. https://bioconductor.org/packages/release/bioc/vignettes/doubletrouble/inst/doc/doubletrouble_vignette.html

Sure, this is indeed what I want. I searched  GitHub before and couldn't find it. I suggest putting it on the homepage of GitHub with an obvious jump link.

Thank you very much for your quick response.

Best regards,
Lin

**Comment by almeidasilvaf** [comment]
It is already there, in the "About" section of the repo's landing page. ;-)

Best,
Fabricio
